#!/usr/bin/env bash

ISSUES_CLOSED_LAST_90_DAYS=$(gh issue list --search "closed:${DATE_90_DAYS_AGO}..${DATE_TODAY}" --limit ${LIMIT} --json author --jq 'length')
ISSUES_CLOSED_PREV_90_DAYS=$(gh issue list --search "closed:${DATE_181_DAYS_AGO}..${DATE_91_DAYS_AGO}" --limit ${LIMIT} --json author --jq 'length')
ISSUES_CLOSED_PERCENTAGE_CHANGE=$(bc <<< "scale=2; ($ISSUES_CLOSED_LAST_90_DAYS-$ISSUES_CLOSED_PREV_90_DAYS)/$ISSUES_CLOSED_PREV_90_DAYS * 100")

echo "ISSUES_CLOSED_LAST_90_DAYS=${ISSUES_CLOSED_LAST_90_DAYS}" >> "$GITHUB_ENV"
echo "ISSUES_CLOSED_PREV_90_DAYS=${ISSUES_CLOSED_PREV_90_DAYS}" >> "$GITHUB_ENV"
echo "ISSUES_CLOSED_PERCENTAGE_CHANGE=${ISSUES_CLOSED_PERCENTAGE_CHANGE}" >> "$GITHUB_ENV"