name: apollo-ios-repo-stats

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 3 * * *"

jobs:
  apollo-ios-repo-stats:
    runs-on: macos-latest
    if: github.repository == 'apollographql/team-prometheus-repo-health-cron'
    steps:
      - name: Checkout Apollo Client
        uses: actions/checkout@v3
        with:
          repository: apollographql/apollo-ios

      # - name: Send a Slack notification
      #   uses: slackapi/slack-github-action@v1.24.0
      #   with:
      #     # Slack channel id, channel name, or user id to post message
      #     # See also: https://api.slack.com/methods/chat.postMessage#channels
      #     # You can pass in multiple channels to post to by providing
      #     # a comma-delimited list of channel IDs
      #     # channel id for #team-prometheus-repository-health
      #     channel-id: "C06EGAW8Q3F"
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
