name: apollo-kotlin-weekly-summary

on:
  schedule:
    - cron: "0 8 * * 3"

jobs:
  apollo-kotlin-weekly-summary:
    runs-on: ubuntu-latest
    if: github.repository == 'apollographql/oss-repo-health-cron'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout Apollo Kotlin repo
        uses: actions/checkout@v4
        with:
          repository: apollographql/apollo-kotlin
          path: apollo-kotlin

      - name: Run get-relative-dates.sh
        run: bash ${GITHUB_WORKSPACE}/main/scripts/get-relative-dates.sh

      - name: Run issues-with-new-comments-last-7-days.sh
        run: cd ${GITHUB_WORKSPACE}/apollo-kotlin && bash ${GITHUB_WORKSPACE}/main/scripts/issues-with-new-comments-last-7-days.sh
        id: issues-new-comments-last-7-days
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run prs-with-new-comments-last-7-days.sh
        run: cd ${GITHUB_WORKSPACE}/apollo-kotlin && bash ${GITHUB_WORKSPACE}/main/scripts/prs-with-new-comments-last-7-days.sh
        id: prs-new-comments-last-7-days
        env:
          REPOSITORY: apollo-kotlin
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_USERS: "-author:BoD -author:martinbonnin -author:app/renovate -author:app/github-actions"

      - name: Send a Slack notification
        uses: slackapi/slack-github-action@v1.25.0
        with:
          # Slack channel id, channel name, or user id to post message
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing
          # a comma-delimited list of channel IDs
          channel-id: ${{ secrets.APOLLO_KOTLIN_SLACK_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Apollo Kotlin weekly rollup :newspaper:\n_Note: This :github: workflow will run every Wednesday at 8AM UTC._"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "Issues with new comments in the last week:\n${{ steps.issues-new-comments-last-7-days.outputs.WEEKLY_SLACK_BOT_MESSAGE_ISSUES }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "PRs with new comments in the last week:\n${{ steps.prs-new-comments-last-7-days.outputs.WEEKLY_SLACK_BOT_MESSAGE_PRS }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
