name: apollo-client-caretaker-handoff

on:
  schedule:
    # Every Wednesday at 4:00 PM UTC
    - cron: "0 16 * * 3"
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref
        required: true
        default: main

jobs:
  apollo-client-caretaker-handoff:
    runs-on: ubuntu-latest
    if: github.repository == 'apollographql/oss-repo-health-cron'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout Apollo Client repo
        uses: actions/checkout@v4
        with:
          repository: apollographql/apollo-client
          path: apollo-client

      - name: Checkout Apollo Client Devtools repo
        uses: actions/checkout@v4
        with:
          repository: apollographql/apollo-client-devtools
          path: apollo-client-devtools

      - name: Checkout Apollo Client Next.js repo
        uses: actions/checkout@v4
        with:
          repository: apollographql/apollo-client-nextjs
          path: apollo-client-nextjs

      - name: Checkout VSCode GraphQL repo
        uses: actions/checkout@v4
        with:
          repository: apollographql/vscode-graphql
          path: vscode-graphql

      - name: Run get-relative-dates.sh
        run: bash ${GITHUB_WORKSPACE}/main/scripts/get-relative-dates.sh

      - name: Run get-apollo-org-members.sh
        run: cd ${GITHUB_WORKSPACE}/apollo-client && bash ${GITHUB_WORKSPACE}/main/scripts/get-apollo-org-members.sh
        env:
          # GH_TOKEN has org:read scope
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run apollo-client-caretaker-handoff.sh
        run: cd ${GITHUB_WORKSPACE}/apollo-client && bash ${GITHUB_WORKSPACE}/main/scripts/apollo-client-caretaker-handoff.sh
        id: caretaker-handoff
        env:
          PD_TOKEN: ${{ secrets.PD_TOKEN }}
          PD_WEB_SCHEDULE_ID: ${{ secrets.PD_WEB_SCHEDULE_ID }}
          JEREL_EMAIL: ${{ secrets.JEREL_EMAIL }}
          ALESSIA_EMAIL: ${{ secrets.ALESSIA_EMAIL }}
          JEFF_EMAIL: ${{ secrets.JEFF_EMAIL }}
          LENZ_EMAIL: ${{ secrets.LENZ_EMAIL }}
          JEREL_SLACK_ID: ${{ secrets.JEREL_SLACK_ID }}
          ALESSIA_SLACK_ID: ${{ secrets.ALESSIA_SLACK_ID }}
          JEFF_SLACK_ID: ${{ secrets.JEFF_SLACK_ID }}
          LENZ_SLACK_ID: ${{ secrets.LENZ_SLACK_ID }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_USER_GROUP: ${{ secrets.SLACK_WEB_CARETAKER_GROUP_ID }}

      - name: Run issues-with-new-comments-last-7-days.sh
        run: cd ${GITHUB_WORKSPACE}/apollo-client && bash ${GITHUB_WORKSPACE}/main/scripts/issues-with-new-comments-last-7-days.sh
        id: issues-new-comments-last-7-days
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run prs-with-new-comments-last-7-days.sh
        run: cd ${GITHUB_WORKSPACE}/apollo-client && bash ${GITHUB_WORKSPACE}/main/scripts/prs-with-new-comments-last-7-days.sh
        id: prs-new-comments-last-7-days
        env:
          REPOSITORY: apollo-client
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_USERS: "-author:alessbell -author:jerelmiller -author:phryneas -author:app/renovate -author:app/github-actions"

      - name: Run issues-percentage-replied-last-90-days.sh for Apollo Client
        id: issues-percentage-replied-last-90-days-apollo-client
        run: cd ${GITHUB_WORKSPACE}/apollo-client && bash ${GITHUB_WORKSPACE}/main/scripts/issues-percentage-replied-last-90-days.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run prs-percentage-replied-last-90-days.sh for Apollo Client
        id: prs-percentage-replied-last-90-days-apollo-client
        run: cd ${GITHUB_WORKSPACE}/apollo-client && bash ${GITHUB_WORKSPACE}/main/scripts/prs-percentage-replied-last-90-days.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: apollo-client

      - name: Run issues-percentage-replied-last-90-days.sh for Apollo Client Devtools
        id: issues-percentage-replied-last-90-days-apollo-client-devtools
        run: cd ${GITHUB_WORKSPACE}/apollo-client-devtools && bash ${GITHUB_WORKSPACE}/main/scripts/issues-percentage-replied-last-90-days.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run prs-percentage-replied-last-90-days.sh for Apollo Client Devtools
        id: prs-percentage-replied-last-90-days-apollo-client-devtools
        run: cd ${GITHUB_WORKSPACE}/apollo-client-devtools && bash ${GITHUB_WORKSPACE}/main/scripts/prs-percentage-replied-last-90-days.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: apollo-client-devtools

      - name: Run issues-percentage-replied-last-90-days.sh for Apollo Client Next.js
        id: issues-percentage-replied-last-90-days-apollo-client-nextjs
        run: cd ${GITHUB_WORKSPACE}/apollo-client-nextjs && bash ${GITHUB_WORKSPACE}/main/scripts/issues-percentage-replied-last-90-days.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run prs-percentage-replied-last-90-days.sh for Apollo Client Next.js
        id: prs-percentage-replied-last-90-days-apollo-client-nextjs
        run: cd ${GITHUB_WORKSPACE}/apollo-client-nextjs && bash ${GITHUB_WORKSPACE}/main/scripts/prs-percentage-replied-last-90-days.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: apollo-client-nextjs

      - name: Run issues-percentage-replied-last-90-days.sh for VSCode GraphQL
        id: issues-percentage-replied-last-90-days-vscode-graphql
        run: cd ${GITHUB_WORKSPACE}/vscode-graphql && bash ${GITHUB_WORKSPACE}/main/scripts/issues-percentage-replied-last-90-days.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run prs-percentage-replied-last-90-days.sh for VSCode GraphQL
        id: prs-percentage-replied-last-90-days-vscode-graphql
        run: cd ${GITHUB_WORKSPACE}/vscode-graphql && bash ${GITHUB_WORKSPACE}/main/scripts/prs-percentage-replied-last-90-days.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: vscode-graphql

      - name: Send a Slack notification
        uses: slackapi/slack-github-action@v1.27.0
        with:
          # Slack channel id, channel name, or user id to post message
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing
          # a comma-delimited list of channel IDs
          channel-id: ${{ secrets.APOLLO_CLIENT_SLACK_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "TypeScript Client caretaker hand-off :running:\nThanks for your help, <@${{ steps.caretaker-handoff.outputs.OUTGOING_CARETAKER_SLACK_HANDLE }}> / hello again, <@${{ steps.caretaker-handoff.outputs.INCOMING_CARETAKER_SLACK_HANDLE }}> :handshake:\n_Note: This :github: workflow will run every Wednesday at 4PM UTC._"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*% issues in last 90d with a reply in <72h*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*% PRs in last 90d with a reply in <72h*"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*`apollo-client`*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "${{ steps.issues-percentage-replied-last-90-days-apollo-client.outputs.PERCENTAGE_ISSUES_REPLIED_TO }}% (${{ steps.issues-percentage-replied-last-90-days-apollo-client.outputs.NUM_ISSUES_REPLIED_TO }}/${{ steps.issues-percentage-replied-last-90-days-apollo-client.outputs.NUM_ISSUES_CREATED }})"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ steps.prs-percentage-replied-last-90-days-apollo-client.outputs.PERCENTAGE_PRS_REPLIED_TO }} (${{ steps.prs-percentage-replied-last-90-days-apollo-client.outputs.NUM_PRS_REPLIED_TO }}/${{ steps.prs-percentage-replied-last-90-days-apollo-client.outputs.NUM_PRS_CREATED }})"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*`apollo-client-devtools`*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "${{ steps.issues-percentage-replied-last-90-days-apollo-client-devtools.outputs.PERCENTAGE_ISSUES_REPLIED_TO }}% (${{ steps.issues-percentage-replied-last-90-days-apollo-client-devtools.outputs.NUM_ISSUES_REPLIED_TO }}/${{ steps.issues-percentage-replied-last-90-days-apollo-client-devtools.outputs.NUM_ISSUES_CREATED }})"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ steps.prs-percentage-replied-last-90-days-apollo-client-devtools.outputs.PERCENTAGE_PRS_REPLIED_TO }} (${{ steps.prs-percentage-replied-last-90-days-apollo-client-devtools.outputs.NUM_PRS_REPLIED_TO }}/${{ steps.prs-percentage-replied-last-90-days-apollo-client-devtools.outputs.NUM_PRS_CREATED }})"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*`apollo-client-nextjs`*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "${{ steps.issues-percentage-replied-last-90-days-apollo-client-nextjs.outputs.PERCENTAGE_ISSUES_REPLIED_TO }}% (${{ steps.issues-percentage-replied-last-90-days-apollo-client-nextjs.outputs.NUM_ISSUES_REPLIED_TO }}/${{ steps.issues-percentage-replied-last-90-days-apollo-client-nextjs.outputs.NUM_ISSUES_CREATED }})"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ steps.prs-percentage-replied-last-90-days-apollo-client-nextjs.outputs.PERCENTAGE_PRS_REPLIED_TO }} (${{ steps.prs-percentage-replied-last-90-days-apollo-client-nextjs.outputs.NUM_PRS_REPLIED_TO }}/${{ steps.prs-percentage-replied-last-90-days-apollo-client-nextjs.outputs.NUM_PRS_CREATED }})"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*`vscode-graphql`*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "${{ steps.issues-percentage-replied-last-90-days-vscode-graphql.outputs.PERCENTAGE_ISSUES_REPLIED_TO }}% (${{ steps.issues-percentage-replied-last-90-days-vscode-graphql.outputs.NUM_ISSUES_REPLIED_TO }}/${{ steps.issues-percentage-replied-last-90-days-vscode-graphql.outputs.NUM_ISSUES_CREATED }})"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ steps.prs-percentage-replied-last-90-days-vscode-graphql.outputs.PERCENTAGE_PRS_REPLIED_TO }} (${{ steps.prs-percentage-replied-last-90-days-vscode-graphql.outputs.NUM_PRS_REPLIED_TO }}/${{ steps.prs-percentage-replied-last-90-days-vscode-graphql.outputs.NUM_PRS_CREATED }})"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Apollo Client issues with new comments in the last week:*\n${{ steps.issues-new-comments-last-7-days.outputs.WEEKLY_SLACK_BOT_MESSAGE_ISSUES }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Apollo Client PRs with new comments in the last week:*\n${{ steps.prs-new-comments-last-7-days.outputs.WEEKLY_SLACK_BOT_MESSAGE_PRS }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
