name: apollo-client-caretaker-handoff

on:
  schedule:
    # Every Wednesday at 8:00 AM PST
    - cron: "0 16 * * 3"

jobs:
  apollo-client-caretaker-handoff:
    runs-on: ubuntu-latest
    if: github.repository == 'apollographql/oss-repo-health-cron'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout Apollo Client repo
        uses: actions/checkout@v4
        with:
          repository: apollographql/apollo-client
          path: apollo-client

      - name: Run get-relative-dates.sh
        run: bash ${GITHUB_WORKSPACE}/main/scripts/get-relative-dates.sh

      - name: Run apollo-client-caretaker-handoff.sh
        run: cd ${GITHUB_WORKSPACE}/apollo-client && bash ${GITHUB_WORKSPACE}/main/scripts/apollo-client-caretaker-handoff.sh
        id: caretaker-handoff
        env:
          PD_TOKEN: ${{ secrets.PD_TOKEN }}
          PD_ORG_ID: ${{ secrets.PD_ORG_ID }}
          JEREL_EMAIL: ${{ secrets.JEREL_EMAIL }}
          ALESSIA_EMAIL: ${{ secrets.ALESSIA_EMAIL }}
          LENZ_EMAIL: ${{ secrets.LENZ_EMAIL }}
          JEREL_SLACK_ID: ${{ secrets.JEREL_SLACK_ID }}
          ALESSIA_SLACK_ID: ${{ secrets.ALESSIA_SLACK_ID }}
          LENZ_SLACK_ID: ${{ secrets.LENZ_SLACK_ID }}

      - name: Run issues-with-new-comments-last-7-days.sh
        run: cd ${GITHUB_WORKSPACE}/apollo-client && bash ${GITHUB_WORKSPACE}/main/scripts/issues-with-new-comments-last-7-days.sh
        id: issues-new-comments-last-7-days
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run prs-with-new-comments-last-7-days.sh
        run: cd ${GITHUB_WORKSPACE}/apollo-client && bash ${GITHUB_WORKSPACE}/main/scripts/prs-with-new-comments-last-7-days.sh
        id: prs-new-comments-last-7-days
        env:
          REPOSITORY: apollo-client
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_USERS: "-author:alessbell -author:jerelmiller -author:phryneas -author:app/renovate -author:app/github-actions"

      - name: Send a Slack notification
        uses: slackapi/slack-github-action@v1.25.0
        with:
          # Slack channel id, channel name, or user id to post message
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing
          # a comma-delimited list of channel IDs
          channel-id: ${{ secrets.APOLLO_CLIENT_SLACK_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Apollo Client caretaker rotation hand-off :running:\nThanks for your help, <@${{ steps.caretaker-handoff.outputs.OUTGOING_CARETAKER_SLACK_HANDLE }}> / hello again, <@${{ steps.caretaker-handoff.outputs.INCOMING_CARETAKER_SLACK_HANDLE }}> :handshake:\n_Note: This :github: workflow will run every Wednesday at 4PM UTC._"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "Issues with new comments in the last week:\n${{ steps.issues-new-comments-last-7-days.outputs.WEEKLY_SLACK_BOT_MESSAGE_ISSUES }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "PRs with new comments in the last week:\n${{ steps.prs-new-comments-last-7-days.outputs.WEEKLY_SLACK_BOT_MESSAGE_PRS }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
