name: apollo-client-repo-stats

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref
        required: true
        default: main
  schedule:
    - cron: "0 12 * * 1-5"

jobs:
  apollo-client-repo-stats:
    runs-on: ubuntu-latest
    if: github.repository == 'apollographql/oss-repo-health-cron'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout Apollo Client repo
        uses: actions/checkout@v4
        with:
          repository: apollographql/apollo-client
          path: apollo-client

      - name: Checkout Apollo Client Devtools repo
        uses: actions/checkout@v4
        with:
          repository: apollographql/apollo-client-devtools
          path: apollo-client-devtools

      - name: Checkout Apollo Client Next.js repo
        uses: actions/checkout@v4
        with:
          repository: apollographql/apollo-client-nextjs
          path: apollo-client-nextjs

      - name: Checkout VSCode GraphQL repo
        uses: actions/checkout@v4
        with:
          repository: apollographql/vscode-graphql
          path: vscode-graphql

      - name: Run get-relative-dates.sh
        run: bash ${GITHUB_WORKSPACE}/main/scripts/get-relative-dates.sh

      - name: Run get-apollo-org-members.sh
        run: cd ${GITHUB_WORKSPACE}/apollo-client && bash ${GITHUB_WORKSPACE}/main/scripts/get-apollo-org-members.sh
        env:
          # GH_TOKEN has org:read scope
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run prs-community-last-90-days.sh
        run: cd ${GITHUB_WORKSPACE}/apollo-client && bash ${GITHUB_WORKSPACE}/main/scripts/prs-community-last-90-days.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run prs-total-merged-last-90-days.sh
        run: cd ${GITHUB_WORKSPACE}/apollo-client && bash ${GITHUB_WORKSPACE}/main/scripts/prs-total-merged-last-90-days.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run issues-closed-last-90-days.sh
        run: cd ${GITHUB_WORKSPACE}/apollo-client && bash ${GITHUB_WORKSPACE}/main/scripts/issues-closed-last-90-days.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run prs-without-replies-last-72-hours.sh for Apollo Client
        id: prs-without-replies-apollo-client
        run: cd ${GITHUB_WORKSPACE}/apollo-client && bash ${GITHUB_WORKSPACE}/main/scripts/prs-without-replies-last-72-hours.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: apollo-client

      - name: Run issues-without-replies-last-72-hours.sh for Apollo Client
        id: issues-without-replies-apollo-client
        run: cd ${GITHUB_WORKSPACE}/apollo-client && bash ${GITHUB_WORKSPACE}/main/scripts/issues-without-replies-last-72-hours.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run prs-without-replies-last-72-hours.sh for Apollo Client Devtools
        id: prs-without-replies-apollo-client-devtools
        run: cd ${GITHUB_WORKSPACE}/apollo-client-devtools && bash ${GITHUB_WORKSPACE}/main/scripts/prs-without-replies-last-72-hours.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: apollo-client-devtools

      - name: Run issues-without-replies-last-72-hours.sh for Apollo Client Devtools
        id: issues-without-replies-apollo-client-devtools
        run: cd ${GITHUB_WORKSPACE}/apollo-client-devtools && bash ${GITHUB_WORKSPACE}/main/scripts/issues-without-replies-last-72-hours.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run prs-without-replies-last-72-hours.sh for Apollo Client Next.js
        id: prs-without-replies-apollo-client-nextjs
        run: cd ${GITHUB_WORKSPACE}/apollo-client-nextjs && bash ${GITHUB_WORKSPACE}/main/scripts/prs-without-replies-last-72-hours.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: apollo-client-nextjs

      - name: Run issues-without-replies-last-72-hours.sh for Apollo Client Next.js
        id: issues-without-replies-apollo-client-nextjs
        run: cd ${GITHUB_WORKSPACE}/apollo-client-nextjs && bash ${GITHUB_WORKSPACE}/main/scripts/issues-without-replies-last-72-hours.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run prs-without-replies-last-72-hours.sh for VSCode GraphQL
        id: prs-without-replies-vscode-graphql
        run: cd ${GITHUB_WORKSPACE}/vscode-graphql && bash ${GITHUB_WORKSPACE}/main/scripts/prs-without-replies-last-72-hours.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: vscode-graphql

      - name: Run issues-without-replies-last-72-hours.sh for VSCode GraphQL
        id: issues-without-replies-vscode-graphql
        run: cd ${GITHUB_WORKSPACE}/vscode-graphql && bash ${GITHUB_WORKSPACE}/main/scripts/issues-without-replies-last-72-hours.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run apollo-client-team-prs-awaiting-review.sh
        id: team-prs-awaiting-review
        run: cd ${GITHUB_WORKSPACE}/apollo-client && bash ${GITHUB_WORKSPACE}/main/scripts/apollo-client-team-prs-awaiting-review.sh
        env:
          # GH_TOKEN has org:read scope
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Send a Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # Slack channel id, channel name, or user id to post message
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing
          # a comma-delimited list of channel IDs
          channel-id: ${{ secrets.APOLLO_CLIENT_SLACK_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Today's TypeScript Client team repository health check :stopwatch:*\n_Note: This :github: workflow will run every weekday at 12PM UTC._"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Issues <72h old without a reply*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*PRs <72h old without a reply*"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*`apollo-client`*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "${{ steps.issues-without-replies-apollo-client.outputs.ISSUES_SLACK_BOT_MESSAGE }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ steps.prs-without-replies-apollo-client.outputs.PRS_SLACK_BOT_MESSAGE }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*`apollo-client-devtools`*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "${{ steps.issues-without-replies-apollo-client-devtools.outputs.ISSUES_SLACK_BOT_MESSAGE }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ steps.prs-without-replies-apollo-client-devtools.outputs.PRS_SLACK_BOT_MESSAGE }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*`apollo-client-nexjs`*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "${{ steps.issues-without-replies-apollo-client-nextjs.outputs.ISSUES_SLACK_BOT_MESSAGE }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ steps.prs-without-replies-apollo-client-nextjs.outputs.PRS_SLACK_BOT_MESSAGE }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*`vscode-graphql`*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "${{ steps.issues-without-replies-vscode-graphql.outputs.ISSUES_SLACK_BOT_MESSAGE }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ steps.prs-without-replies-vscode-graphql.outputs.PRS_SLACK_BOT_MESSAGE }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Team PRs awaiting review:*${{ steps.team-prs-awaiting-review.outputs.TEAM_PRS_AWAITING_REVIEW_MARKDOWN }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
