name: apollo-client-repo-stats

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 3 * * *"

jobs:
  apollo-client-repo-stats:
    runs-on: macos-latest
    if: github.repository == 'apollographql/team-prometheus-repo-health-cron'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: apollographql/apollo-client
          path: apollo-client

      - run: cd apollo-client && ls -la && bash ${GITHUB_WORKSPACE}/main/scripts/get-relative-dates.sh

      - run: echo "$DATE_181_DAYS_AGO"

        env:
          # GH_TOKEN is a PAT with org:read scope
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # - name: Send a Slack notification
      #   uses: slackapi/slack-github-action@v1.24.0
      #   with:
      #     # Slack channel id, channel name, or user id to post message
      #     # See also: https://api.slack.com/methods/chat.postMessage#channels
      #     # You can pass in multiple channels to post to by providing
      #     # a comma-delimited list of channel IDs
      #     # channel id for #team-prometheus-repository-health
      #     channel-id: "C06EGAW8Q3F"
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
