name: keep-active
on:
  schedule:
    - cron: "1 1 1 * *"
  workflow_dispatch:
jobs:
  keep-active:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Commit empty commit
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit --allow-empty -m "chore: one commit a month to keep cronjob actions running"
          git push
